/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kwang_kaldiandroid_util_KaldiUtil */

#ifndef _Included_com_example_kwang_kaldiandroid_util_KaldiUtil
#define _Included_com_example_kwang_kaldiandroid_util_KaldiUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kwang_kaldiandroid_util_KaldiUtil
 * Method:    startEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_kwang_kaldiandroid_util_KaldiUtil_startEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_kwang_kaldiandroid_util_KaldiUtil
 * Method:    stopEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_kwang_kaldiandroid_util_KaldiUtil_stopEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_kwang_kaldiandroid_util_KaldiUtil
 * Method:    startRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_kwang_kaldiandroid_util_KaldiUtil_startRecognition
  (JNIEnv *, jclass);

/*
 * Class:     com_example_kwang_kaldiandroid_util_KaldiUtil
 * Method:    stopRecognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_kwang_kaldiandroid_util_KaldiUtil_stopRecognition
  (JNIEnv *, jclass);

/*
 * Class:     com_example_kwang_kaldiandroid_util_KaldiUtil
 * Method:    getResultString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_kwang_kaldiandroid_util_KaldiUtil_getResultString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
